name: Accessibility Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Accessibility Audit
      run: |
        npm install -g pa11y-ci
        pa11y-ci --sitemap https://borderlinepersonalitidisorder.github.io/NEPTUNO/sitemap.xml